name: Build Magento Nginx image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths:
      - images/nginx/**

  pull_request:
    branches: [ "main" ]
    paths:
      - images/nginx/**

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      image_name: ${{ github.repository }}/nginx
      context: ./images/nginx
      publish: ${{ github.event_name != 'pull_request'}}
      registry: ghcr.io
